# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        env:
          DEPLOY_SECRET_KEY: ${{ secrets.DEPLOY_SECRET_KEY}}
          BRANCH: ${{ github.ref.name}}
        run: |
          echo $BRANCH
          mkdir -p $BRANCH
          touch $BRANCH/`date +%Y%m%d_%H%M%S`
          echo "$DEPLOY_SECRET_KEY" > ~/.deploykey.pem
          wc ~/.deploykey.pem
          ls
          ls $BRANCH
          pwd
